[Metadata]
Name=Nightscout
Version=1.0

[styleTitle]
StringAlign=Center
StringCase=Upper
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#colorText#
FontFace=#fontName#
FontSize=15
AntiAlias=1
ClipString=1

[styleCenterText]
StringAlign=Center
X=200
H=50
; Meters using styleLeftText will be left-aligned.
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleSeperator]
SolidColor=255,255,255,15

[MeasureTime]
Measure=Time
Format=%H%M%S

[Data]
Measure=Plugin
Plugin=WebParser.dll
URL=https://#DOMAIN#/api/v1/entries/?count=2&token=#TOKEN#&_ts=[&MeasureTime]  ; if you dont have ssl on server use http
Header=Accept: application/json
RegExp=(?siU)^(.*)$
UpdateRate=1
DynamicVariables=1
FinishAction=[!EnableMeasure "SGVParserBG"][!EnableMeasure "SGVParserPrevBG"][!EnableMeasure "SGVParserBGDate"][!EnableMeasure "SGVParserBGArrow"][!UpdateMeasure "SGVParserBG"][!UpdateMeasure "SGVParserPrevBG"][!UpdateMeasure "SGVParserBGDate"][!UpdateMeasure "SGVParserBGArrow"][!EnableMeasure "TrendArrowScript"][!EnableMeasure "EpochConvertScript"][!UpdateMeasure "TrendArrowScript"][!UpdateMeasure "EpochConvertScript"][!UpdateMeasure "MeasureBG"][!UpdateMeasure "MeasureBGDelta"][!UpdateMeasure "MeasureBGState"][!UpdateMeasure "MeasureBGColorLogic"][!UpdateMeter *][!Redraw]

[Rainmeter]
; This section contains general settings that can be used to change how Rainmeter behaves.
Update=5000
SolidColor=0,0,0,1
DynamicWindowSize=1
AccurateText=1

[Variables]
; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
TOKEN = <replace-with-your-nightscout-token>    ;<<-------------------------
DOMAIN = <replace-with-your-nightscout-domain>   ;<<-------------------------
fontName=Comfortaa
textSize=20
colorBar=235,170,0,255
colorText=255,255,255,205

colorNormal=0,255,0,205      ; Color for normal sugar level 
colorHigh=255,255,0,205      ; Color for High sugar level 
colorLow=255,0,0,205         ; Color for ow sugar level 

; thr for mg/dL
;lowThr=70
;highThr=180  

; thr for mmol/l
lowThr=3.9
highThr=10

; Units:
; mmol/L -> unitFactor=0.0555, unitLabel=mmol/l
; mg/dL  -> unitFactor=1,      unitLabel=mg/dL
unitFactor=0.0555
unitLabel=mmol/l

[SGVParserBG]
Measure=Plugin
Plugin=JsonParser.dll
Source=[Data]
Logging=NoMatch:1,EmptySource:1
Query="[0].sgv"
DynamicVariables=1
Disabled=1

[SGVParserPrevBG]
DynamicVariables=1
Measure=Plugin
Plugin=JsonParser.dll
Source=[Data]
Logging=NoMatch:1,EmptySource:1
Query="[1].sgv"
DynamicVariables=1
Disabled=1

[SGVParserBGDate]
Measure=Plugin
Plugin=JsonParser.dll
Source=[Data]
Logging=NoMatch:1,EmptySource:1
Query="[0].date"
DynamicVariables=1
Disabled=1

[SGVParserBGArrow]
Measure=Plugin
Plugin=JsonParser.dll
Source=[Data]
Logging=NoMatch:1,EmptySource:1
Query="[0].direction"
UpdateRate=50100
DynamicVariables=1
Disabled=1

[MeasureBG]
Measure=Calc
Formula=SGVParserBG*#unitFactor#
DynamicVariables=1

[MeasureBGDelta]
Measure=Calc
Formula=(SGVParserBG - SGVParserPrevBG)*#unitFactor#
DynamicVariables=1

[TrendArrowScript]
Measure=Script
ScriptFile=TrendArrow.lua
DynamicVariables=1
Disabled=1

[EpochConvertScript]
Measure=Script
ScriptFile=EpochConvert.lua
UpdateRate=1
DynamicVariables=1
Disabled=1

[MeasureBGState]
Measure=Calc
Formula=(MeasureBG < #lowThr# ? 0 : (MeasureBG > #highThr# ? 2 : 1))
DynamicVariables=1
;OnUpdateAction=[!Log "BG State: [MeasureBGState] BG=[MeasureBG]" "Notice"]

[MeasureBGColorLogic]
Measure=Calc
Formula=MeasureBGState
DynamicVariables=1

IfCondition=(MeasureBGState = 0)
IfTrueAction=[!SetOption SVGMeter FontColor "#colorLow#"][!UpdateMeter SVGMeter][!Redraw]

IfCondition2=(MeasureBGState = 1)
IfTrueAction2=[!SetOption SVGMeter FontColor "#colorNormal#"][!UpdateMeter SVGMeter][!Redraw]

IfCondition3=(MeasureBGState = 2)
IfTrueAction3=[!SetOption SVGMeter FontColor "#colorHigh#"][!UpdateMeter SVGMeter][!Redraw]

[SVGMeter]
Meter=String
MeterStyle=styleCenterText
MeasureName=MeasureBG
FontSize=36
H=70
W=500
Y=50
X=175
Text=%1 #unitLabel#
AntiAlias=1
NumOfDecimals=1
DynamicVariables=1
FontColor=#colorText#

[MeterArrow]
Meter=String
MeasureName=MeasureBG
StringAlign=Left
MeterStyle=styleCenterText
FontSize=25
X=0
Y=65
AntiAlias=1
DynamicVariables=1

[MeterDate]
Meter=String
MeasureName=SGVParserBGDate
MeterStyle=styleCenterText
StringAlign=Left
X=40
Y=115
AntiAlias=1
DynamicVariables=1

[MeterBGDelta]
Meter=String
MeasureName=MeasureBGDelta
MeterStyle=styleCenterText
StringAlign=Left
X=230
Y=115
AntiAlias=1
DynamicVariables=1


